services:
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - ~/config/Emby:/config
      - ~/movies:/data/movies
      - ~/downloads:/data/tvshows
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped

  embystat:
    image: ghcr.io/linuxserver/embystat
    container_name: embystat
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Sao_Paulo
    volumes:
      - ~/config/EmbyStat:/config
    ports:
      - 6555:6555
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Sao_Paulo
    volumes:
      - ~/config/Jackett:/config
      - ~/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr
    restart: unless-stopped
    ports:
        - 90:80
    volumes:
        - ~/config/Organizr:/config
    environment:
        - fpm=true
        - branch=v2-master
        - PUID=998
        - PGID=100
        - TZ=America/Sao_Paulo

  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true
    environment:
      - VPN_USERNAME=username
      - VPN_PASSWORD=password
      - PUID=998
      - PGID=100
      - WEBUI_PORT_ENV=8081
      - INCOMING_PORT_ENV=8999
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.68.0/24
      - NAME_SERVERS=1.1.1.1,1.0.0.1
    ports:
      - 8081:8081
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - ~/config/QBittorrentVPN:/config
      - ~/downloads:/downloads
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - ~/config/Radarr:/config
      - ~/movies:/movies
      - ~/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Sao_Paulo
    volumes:
      - ~/config/Sabnzbd:/config
      - ~/downloads:/downloads
      - ~/downloads/Incomplete:/incomplete-downloads
    ports:
      - 8181:8080
      - 9191:9090
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - ~/config/Sonarr:/config
      - ~/tv:/tv
      - ~/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

## System Monitoring

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      environment:
        - PUID=998
        - PGID=100
        - TZ=America/Sao_Paulo
        - UMASK_SET=022
      volumes:
        - ~/config/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - 9292:9090
      restart: unless-stopped

  node-exporter:
      image: quay.io/prometheus/node-exporter:latest
      container_name: node-exporter
      network_mode: host
      environment:
        - PUID=998
        - PGID=100
        - TZ=America/Sao_Paulo
        - UMASK_SET=022
      volumes:
        - /:/host:ro,rslave
      ports:
        - 9100:9090
      restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    ports:
      - 3000:3000
    restart: unless-stopped
